/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.time.LocalDate;
import model.UberHistory;
import model.Uber;

/**
 *
 * @author Sri Vyshnavi
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    UberHistory history;

    public MainJFrame() {
        initComponents();

        history = new UberHistory();
        setData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPane = new javax.swing.JSplitPane();
        controlPanel = new javax.swing.JPanel();
        btnCreate = new javax.swing.JButton();
        btnView = new javax.swing.JButton();
        workArea = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        controlPanel.setBackground(new java.awt.Color(51, 51, 51));

        btnCreate.setText("Create Car");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        btnView.setText("View Car");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout controlPanelLayout = new javax.swing.GroupLayout(controlPanel);
        controlPanel.setLayout(controlPanelLayout);
        controlPanelLayout.setHorizontalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(btnView, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCreate))
        );
        controlPanelLayout.setVerticalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(btnCreate)
                .addGap(75, 75, 75)
                .addComponent(btnView)
                .addContainerGap())
        );

        splitPane.setLeftComponent(controlPanel);

        workArea.setBackground(new java.awt.Color(246, 207, 207));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        jLabel1.setText("CAR MANAGEMENT SYSTEM");

        javax.swing.GroupLayout workAreaLayout = new javax.swing.GroupLayout(workArea);
        workArea.setLayout(workAreaLayout);
        workAreaLayout.setHorizontalGroup(
            workAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(workAreaLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 695, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        workAreaLayout.setVerticalGroup(
            workAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(workAreaLayout.createSequentialGroup()
                .addGap(193, 193, 193)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(599, Short.MAX_VALUE))
        );

        splitPane.setRightComponent(workArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
        ViewJPanel viewPanel = new ViewJPanel(history);
        splitPane.setRightComponent(viewPanel);
    }//GEN-LAST:event_btnViewActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
        CreateJPanel createPanel = new CreateJPanel(history);
        splitPane.setRightComponent(createPanel);

    }//GEN-LAST:event_btnCreateActionPerformed
    public void setData() {

        Uber uc = history.addNewCars();

        uc.setModelName("HRV");
        uc.setvinNumber(10991);
        uc.setManufacturer("Toyota");
        uc.setManufacturedDate(LocalDate.parse("2014-04-01"));
        uc.setSeatCapacity(7);
        uc.setUsedBy("Uber");
        uc.setIsAvailable(true);
        uc.setLastUpdated("17-08-2015");
        uc.setCity("California");
        uc.setMaintenanceCertExpDate(LocalDate.parse("2023-10-11"));

        Uber c1 = history.addNewCars();

        c1.setModelName("GLC 300");
        c1.setvinNumber(10291);
        c1.setManufacturer("Mercedes Benz");
        c1.setManufacturedDate(LocalDate.parse("2010-01-02"));
        c1.setSeatCapacity(4);
        c1.setUsedBy("Ola");
        c1.setIsAvailable(false);
        c1.setLastUpdated("02-09-2020");
        c1.setCity("Rhode Island");
        c1.setMaintenanceCertExpDate(LocalDate.parse("2023-02-23"));

        Uber c2 = history.addNewCars();

        c2.setModelName("Xuv500");
        c2.setvinNumber(9087);
        c2.setManufacturer("Mahindra");
        c2.setManufacturedDate(LocalDate.parse("2012-03-07"));
        c2.setSeatCapacity(6);
        c2.setUsedBy("Ola");
        c2.setIsAvailable(true);
        c2.setLastUpdated("01-02-2021");
        c2.setCity("Arizona");
        c2.setMaintenanceCertExpDate(LocalDate.parse("2023-07-02"));

        Uber c3 = history.addNewCars();

        c3.setModelName("A6");
        c3.setvinNumber(1122);
        c3.setManufacturer("Audi");
        c3.setManufacturedDate(LocalDate.parse("2018-07-01"));
        c3.setSeatCapacity(3);
        c3.setUsedBy("Uber");
        c3.setIsAvailable(false);
        c3.setLastUpdated("12-11-2013");
        c3.setCity("Texas");
        c3.setMaintenanceCertExpDate(LocalDate.parse("2018-12-12"));

        Uber c4 = history.addNewCars();

        c4.setModelName("CX5");
        c4.setvinNumber(2900);
        c4.setManufacturer("Cheverlot");
        c4.setManufacturedDate(LocalDate.parse("2011-01-02"));
        c4.setSeatCapacity(5);
        c4.setUsedBy("Uber");
        c4.setIsAvailable(false);
        c4.setLastUpdated("01-02-2009");
        c4.setCity("Pheonix");
        c4.setMaintenanceCertExpDate(LocalDate.parse("2011-08-11"));

        Uber c5 = history.addNewCars();

        c5.setModelName("City");
        c5.setvinNumber(8744);
        c5.setManufacturer("Honda");
        c5.setManufacturedDate(LocalDate.parse("2016-08-04"));
        c5.setSeatCapacity(5);
        c5.setUsedBy("Uber");
        c5.setIsAvailable(false);
        c5.setLastUpdated("08-01-2018");
        c5.setCity("Portland");
        c5.setMaintenanceCertExpDate(LocalDate.parse("2017-02-01"));
        
        Uber c6 = history.addNewCars();

        c6.setModelName("Urus");
        c6.setvinNumber(2278);
        c6.setManufacturer("Lamborghini");
        c6.setManufacturedDate(LocalDate.parse("2018-09-08"));
        c6.setSeatCapacity(2);
        c6.setUsedBy("Lyft");
        c6.setIsAvailable(true);
        c6.setLastUpdated("06-09-2017");
        c6.setCity("Amherst");
        c6.setMaintenanceCertExpDate(LocalDate.parse("2019-09-10"));
       

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnView;
    private javax.swing.JPanel controlPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSplitPane splitPane;
    private javax.swing.JPanel workArea;
    // End of variables declaration//GEN-END:variables
}
