/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.io.File;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import model.PersonalProfile;

/**
 *
 * @author srivyshnavi
 */

public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    String imageView;
    PersonalProfile personal;
    
    public CreateJPanel(PersonalProfile personal) {
        initComponents();
        this.personal = personal;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelCreate = new javax.swing.JLabel();
        labelName = new javax.swing.JLabel();
        labelGeoData = new javax.swing.JLabel();
        labelDOB = new javax.swing.JLabel();
        labelTelephone = new javax.swing.JLabel();
        labelFax = new javax.swing.JLabel();
        labelEmail = new javax.swing.JLabel();
        labelSSN = new javax.swing.JLabel();
        labelMedical = new javax.swing.JLabel();
        labelHealthPlan = new javax.swing.JLabel();
        labelBankAcc = new javax.swing.JLabel();
        labelCertificate = new javax.swing.JLabel();
        labelVehicle = new javax.swing.JLabel();
        labelDevice = new javax.swing.JLabel();
        labelLinkedIn = new javax.swing.JLabel();
        labelIP = new javax.swing.JLabel();
        labelBiometric = new javax.swing.JLabel();
        labelPhoto = new javax.swing.JLabel();
        labelUnique = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtGeoData = new javax.swing.JTextField();
        txtTelephone = new javax.swing.JTextField();
        txtFax = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtSSN = new javax.swing.JTextField();
        txtMedical = new javax.swing.JTextField();
        txtHealthPlan = new javax.swing.JTextField();
        txtBankAcc = new javax.swing.JTextField();
        txtCertificate = new javax.swing.JTextField();
        txtVehicle = new javax.swing.JTextField();
        txtDevice = new javax.swing.JTextField();
        txtLinkedIn = new javax.swing.JTextField();
        txtIP = new javax.swing.JTextField();
        txtBiometric = new javax.swing.JTextField();
        txtUnique = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnPhoto = new javax.swing.JButton();
        DateofBirth = new org.jdesktop.swingx.JXDatePicker();

        labelCreate.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        labelCreate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelCreate.setText("CREATE");

        labelName.setText("Name :");

        labelGeoData.setText("Geographic Data :");

        labelDOB.setText("Date of Birth :");

        labelTelephone.setText("Telephone Number :");

        labelFax.setText("FAX Number :");

        labelEmail.setText("Email Addresses :");

        labelSSN.setText("Social Security Number :");

        labelMedical.setText("Medical Record Number :");

        labelHealthPlan.setText("Health Plan Beneficiary Number:");

        labelBankAcc.setText("Bank Account Numbers:");

        labelCertificate.setText("Certificate/License Numbers :");

        labelVehicle.setText("Vehicle Identifiers and Serial Numbers :");

        labelDevice.setText("Device Identifiers and Serial Numbers :");

        labelLinkedIn.setText("LinkedIn :");

        labelIP.setText("IP Address :");

        labelBiometric.setText("Biometric Identifiers : ");

        labelPhoto.setText("Full face photos & comparable images:");

        labelUnique.setText("Unique Identifying Number :");

        txtCertificate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCertificateActionPerformed(evt);
            }
        });

        btnSave.setText("SAVE");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnPhoto.setText("Upload Photo");
        btnPhoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPhotoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelCreate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(labelSSN)
                                    .addComponent(labelMedical)
                                    .addComponent(labelHealthPlan))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtMedical, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                                    .addComponent(txtHealthPlan))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(labelUnique))
                                    .addComponent(labelPhoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(74, 74, 74)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(labelName)
                                    .addComponent(labelGeoData)
                                    .addComponent(labelDOB)
                                    .addComponent(labelTelephone)
                                    .addComponent(labelFax)
                                    .addComponent(labelEmail))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtSSN)
                                    .addComponent(txtFax)
                                    .addComponent(txtEmail)
                                    .addComponent(txtTelephone, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtGeoData, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtName, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(DateofBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(labelCertificate)
                                    .addComponent(labelBankAcc)
                                    .addComponent(labelVehicle)
                                    .addComponent(labelDevice)
                                    .addComponent(labelLinkedIn)
                                    .addComponent(labelIP)
                                    .addComponent(labelBiometric, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtBankAcc, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCertificate, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtVehicle, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDevice, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtBiometric)
                                    .addComponent(txtIP)
                                    .addComponent(txtLinkedIn)
                                    .addComponent(txtUnique))
                                .addGap(8, 8, 8))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnPhoto)
                                .addGap(0, 6, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(334, 334, 334)
                .addComponent(btnSave)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(labelCreate)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelBankAcc)
                    .addComponent(txtBankAcc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelGeoData)
                    .addComponent(txtGeoData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCertificate)
                    .addComponent(txtCertificate, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDOB)
                    .addComponent(txtVehicle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelVehicle)
                    .addComponent(DateofBirth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDevice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelTelephone)
                        .addComponent(txtTelephone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelDevice)))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelFax)
                    .addComponent(txtFax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelLinkedIn)
                    .addComponent(txtLinkedIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEmail)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelIP)
                    .addComponent(txtIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSSN)
                    .addComponent(txtSSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelBiometric)
                    .addComponent(txtBiometric, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMedical)
                    .addComponent(txtMedical, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelPhoto)
                    .addComponent(btnPhoto))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelHealthPlan)
                    .addComponent(txtHealthPlan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelUnique)
                    .addComponent(txtUnique, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(btnSave)
                .addGap(22, 22, 22))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtCertificateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCertificateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCertificateActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        personal.setName(txtName.getText());
        personal.setGeographicData(txtGeoData.getText());
        Date oDate = DateofBirth.getDate();
        personal.setDob(oDate);
        personal.setPhNum(txtTelephone.getText());
        personal.setFaxNum(Integer.parseInt(txtFax.getText()));
        personal.setEmail(txtEmail.getText());
        personal.setSSN(Integer.parseInt(txtSSN.getText()));
        personal.setMedical(Integer.parseInt(txtMedical.getText()));
        personal.setHealth(Integer.parseInt(txtHealthPlan.getText()));
        personal.setBankAcc(Integer.parseInt(txtBankAcc.getText()));
        personal.setCertNum(Integer.parseInt(txtCertificate.getText()));
        personal.setVehicleId(Integer.parseInt(txtVehicle.getText()));
        personal.setDeviceId(Integer.parseInt(txtDevice.getText()));
        personal.setLinkedIn(txtLinkedIn.getText());
        personal.setIP(txtIP.getText());
        personal.setBiometric(txtBiometric.getText());
        personal.setUniqueID(Integer.parseInt(txtUnique.getText()));
        personal.setImageDisplay(imageView);
        
        
        JOptionPane.showMessageDialog(this, "Personal Profile Information Saved");
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnPhotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPhotoActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter( "3 Extensions Supported " , ".jpg" , ".png." , "jpeg" );
        fileChooser.setFileFilter(filter);
        int selected = fileChooser.showOpenDialog(this);
        
        if(selected == JFileChooser.APPROVE_OPTION){
            File file = fileChooser.getSelectedFile();
            String getSelectedImage = file.getAbsolutePath();
            imageView = getSelectedImage;
            JOptionPane.showMessageDialog(null, getSelectedImage);
        }
        
    }//GEN-LAST:event_btnPhotoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXDatePicker DateofBirth;
    private javax.swing.JButton btnPhoto;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel labelBankAcc;
    private javax.swing.JLabel labelBiometric;
    private javax.swing.JLabel labelCertificate;
    private javax.swing.JLabel labelCreate;
    private javax.swing.JLabel labelDOB;
    private javax.swing.JLabel labelDevice;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelFax;
    private javax.swing.JLabel labelGeoData;
    private javax.swing.JLabel labelHealthPlan;
    private javax.swing.JLabel labelIP;
    private javax.swing.JLabel labelLinkedIn;
    private javax.swing.JLabel labelMedical;
    private javax.swing.JLabel labelName;
    private javax.swing.JLabel labelPhoto;
    private javax.swing.JLabel labelSSN;
    private javax.swing.JLabel labelTelephone;
    private javax.swing.JLabel labelUnique;
    private javax.swing.JLabel labelVehicle;
    private javax.swing.JTextField txtBankAcc;
    private javax.swing.JTextField txtBiometric;
    private javax.swing.JTextField txtCertificate;
    private javax.swing.JTextField txtDevice;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFax;
    private javax.swing.JTextField txtGeoData;
    private javax.swing.JTextField txtHealthPlan;
    private javax.swing.JTextField txtIP;
    private javax.swing.JTextField txtLinkedIn;
    private javax.swing.JTextField txtMedical;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtSSN;
    private javax.swing.JTextField txtTelephone;
    private javax.swing.JTextField txtUnique;
    private javax.swing.JTextField txtVehicle;
    // End of variables declaration//GEN-END:variables
}
